**Batch** 
* batch(X, Y, batch_size = int)  
* X : Matrix where no. of rows = n_features, and no. of columns = m_samples (NXM) 
* Y : Row Vector where no. of columns = m_samples 
* batch_size : Defining submatrix of X, where no. of rows = n_features, and no. of columns = int

In [1]:
import numpy as np 

In [34]:
X = np.arange(100).reshape(10,10)
Y = np.random.randn(10).reshape(1,10)

X,Y, Y.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]),
 array([[-1.08647014,  1.16679063, -1.50745711, -1.54701573, -0.07718016,
         -0.77062114, -1.98635658, -0.33275631,  0.17447481, -1.40737886]]),
 (1, 10))

In [35]:
def batch(X, Y, size = 3):
    
    start = 0 
    end = size 
    
    for i in range (int(X.shape[1]/size) + 1): 
        
        xbatch = X[0:X.shape[0], start:end]
        ybatch = Y[0, start:end]
        #Instead of printing, can we externally save "batch i"?   
        print("batch {}".format(i))
        print("--------")
        print("X:", xbatch)
        print("Y:", ybatch)
        print()
        
        start += size 
        end += size

batch(X, Y, size = 3)

batch 0
--------
X: [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]
 [50 51 52]
 [60 61 62]
 [70 71 72]
 [80 81 82]
 [90 91 92]]
Y: [-1.08647014  1.16679063 -1.50745711]
batch 1
--------
X: [[ 3  4  5]
 [13 14 15]
 [23 24 25]
 [33 34 35]
 [43 44 45]
 [53 54 55]
 [63 64 65]
 [73 74 75]
 [83 84 85]
 [93 94 95]]
Y: [-1.54701573 -0.07718016 -0.77062114]
batch 2
--------
X: [[ 6  7  8]
 [16 17 18]
 [26 27 28]
 [36 37 38]
 [46 47 48]
 [56 57 58]
 [66 67 68]
 [76 77 78]
 [86 87 88]
 [96 97 98]]
Y: [-1.98635658 -0.33275631  0.17447481]
batch 3
--------
X: [[ 9]
 [19]
 [29]
 [39]
 [49]
 [59]
 [69]
 [79]
 [89]
 [99]]
Y: [-1.40737886]


**Initialize**

In [9]:
n_features = 10 

def initialize_parameters(n_features): 
    weight = np.random.randn(n_features,1)
    bias = np.random.randn(1)
    return weight, bias 

weight, bias = initialize_parameters(n_features)
weight, bias 

(array([[-1.31580058],
        [-1.53575282],
        [-1.11462306],
        [ 3.23856131],
        [ 0.22403524],
        [-0.40690645],
        [-0.32455089],
        [ 1.81276063],
        [-0.47460361],
        [ 1.77474713]]),
 array([-1.47886832]))

**Shuffle** 

In [ ]:
"""Depending on the structure of the package, 
random_idx = np.arange(m_samples)
np.random.shuffle(random_idx)
random_idx.reshape(1,m_samples)

X_shuffled = np.empty([n_features, m_samples ])

for i in range (m_samples): 
    X_shuffled[:,i] = X[:,random_idx[i]]"""

def shuffle(X): 
    random_idx = np.arange(X.shape[1])
    np.random.shuffle(random_idx)
    random_idx.reshape(1,X.shape[1])
    
    X_shuffled = np.empty([X.shape[0], X.shape[1]])
    
    for i in range (X.shape[1]): 
        X_shuffled[:,i] = X[:,random_idx[i]]
    
    return X_shuffled 