In [1]:
import numpy as np
import scipy as sp
import scipy.stats
import matplotlib.pylab as plt

In [9]:
%%writefile propagate.py
import numpy as np 

class affine_function: 
    
    def __init__(self): 
        self.w, self.b = None, None 
        self.y_hat = None 
    
    def forward(self, w, b, x): 
        self.w, self.b, self.x = w, b, x  
        self.y_hat = np.dot(self.w.T, self.x) + self.b
        return self.y_hat 
    
    def backward(self, dvoi):  
        self.dw = np.dot(dvoi, self.x.T) 
        
        self.db = np.ones((self.x.shape[1],1))
        self.db = np.dot(dvoi,self.db) 
        return self.dw, self.db 

class loss_function: 
    
    def __init__(self): 
        self.y, self.y_hat = None, None 
        self.loss = None 
    
    def forward(self, y, y_hat): 
        self.y, self.y_hat = y, y_hat 
        self.loss = (self.y - self.y_hat)**2 
        return self.loss 
    
    def backward(self, dvoi): 
        self.dy_hat = -2 * (self.y - self.y_hat)
        self.dy_hat = np.diag(self.dy_hat[0])
        self.dy_hat = np.dot(dvoi,self.dy_hat)
        return self.dy_hat

class cost_function: 
    def __init__(self): 
        self.loss = None 
        self.cost = None 
        
    def forward(self, loss): 
        self.loss = loss 
        self.cost = np.mean(loss)
        return self.cost 
    
    def backward(self, sample_size, dvoi): 
        self.dloss = 1/sample_size * np.ones((1,sample_size))
        self.dloss = dvoi * self.dloss
        return self.dloss

Overwriting propagate.py


In [6]:
import propagate

affine = propagate.affine_function()
loss = propagate.loss_function()
cost = propagate.cost_function()

In [7]:
weight_update = []
bias_update = [] 
cost_update = [] 

for i in range(0,5): 
    #shuffle columns(samples) of X 
    x, y = X, Y 
    
    y_hat = affine.forward(weight, bias, x)
    L = loss.forward(y, y_hat)
    J = cost.forward(L)
            
    dL = cost.backward(sample_size = m_samples, dvoi=1)
    dy_hat = loss.backward(dL)
    dw, db = affine.backward(dy_hat)
            
    dw, db = np.sum(dw), np.sum(db)
            
    weight -= lr*dw 
    bias -= lr*db
            
    weight_update.append(weight)
    bias_update.append(bias)
    cost_update.append(cost)

In [8]:
weight_update, bias_update, cost_update

([array([[153.7309987]]),
  array([[153.7309987]]),
  array([[153.7309987]]),
  array([[153.7309987]]),
  array([[153.7309987]])],
 [array([22.05367743]),
  array([22.05367743]),
  array([22.05367743]),
  array([22.05367743]),
  array([22.05367743])],
  <propagate.cost_function at 0x1ae6249bd88>])

In [11]:
x, y = X, Y 
    
y_hat = affine.forward(weight, bias, x)
print(y_hat)
L = loss.forward(y, y_hat)
print(L)
J = cost.forward(L)
print(J)
            
dL = cost.backward(sample_size = m_samples, dvoi=1)
print(dL)
dy_hat = loss.backward(dL)
print(dy_hat)
dw, db = affine.backward(dy_hat)
            
dw, db = np.sum(dw), np.sum(db)
print(dw,db)
            
weight -= lr*dw 
bias -= lr*db
print(weight,bias)

[[91.99189311 92.08027778 92.16866245 92.25704713 92.3454318  92.43381647
  92.52220115 92.61058582 92.69897049 92.78735516]]
[[8522.69342488 8447.59147284 8613.09446882 8349.2420583  8555.04948094
  8254.67006481 8341.56231435 8512.25135682 8914.32210568 8702.36771465]]
8521.284446207592
[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]
[[18.46368698 18.38215599 18.56135175 18.27483741 18.4987021  18.17104297
  18.26643076 18.45237259 18.88313756 18.65729639]]
91404.2100812961 184.61101449965878
[[-4569.49824409]
 [-4570.2548371 ]
 [-4569.85642111]
 [-4572.21857485]
 [-4570.41318805]
 [-4570.94641684]
 [-4571.41261444]
 [-4569.48605842]
 [-4569.07827409]
 [-4568.85202697]] [-10.15777261]
